# dockerfile install buildx
FROM docker:stable
RUN mkdir -p ~/.docker/cli-plugins && \
    cd ~/.docker/cli-plugins && \
    wget https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-amd64 && \
    chmod a+x buildx-v0.6.1.linux-amd64 && \
    mv buildx-v0.6.1.linux-amd64 docker-buildx && \
    docker buildx install