apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitor
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: filebeat
data:
  filebeat.yml: |-
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false

    setup.kibana:
      host: "http://10.15.133.21:5601"

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - "/var/log/containers/${data.kubernetes.pod.name}_${data.kubernetes.namespace}_${data.kubernetes.container.name}-${data.kubernetes.container.id}.log"
            exclude_lines: ["^\\s+[\\-`('.|_]"]

    processors:
      - drop_fields:
          fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "agent.name", "ecs.version", "input.type", "log.offset", "stream"]

    setup.template:
      enabled: true
      name: "filebeat-%{[agent.version]}"
      pattern: "filebeat-*"
      overwrite: true

    setup.ilm.enabled: false

    logging.metrics.enabled: false

    output.elasticsearch:
      hosts:
        - "http://10.15.133.21:9200"
      username: "elastic"
      password: "qHRHw+xLbzEXlMv3hcTu"
      indices:
        - index: "mykiot-app-%{+yyyy.MM.dd}"
          when:
            equals:
              kubernetes.namespace: "mykiot"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: monitor  
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: filebeat
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elastic
      app.kubernetes.io/component: filebeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elastic
        app.kubernetes.io/component: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.5
        args:
        - "-c"
        - "/etc/filebeat.yml"
        - "-e"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: observability
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat
  namespace: monitor  
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: observability
roleRef:
  kind: Role
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: filebeat
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs:
  - get
  - watch
  - list
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat
  namespace: monitor  
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: filebeat
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: monitor  
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: filebeat
