for elasticsearch version 7.4.2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: kibana
data:
  kibana.yml: |-
    server:
      host: 0.0.0.0

    elasticsearch:
      hosts:
        - "http://elasticsearch:9200"
        - "http://elasticsearch2:9200"
        - "http://elasticsearch3:9200"
      username: kibana
      password: yrk6WN1jjGU5oABDgkj9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: kibana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elastic
      app.kubernetes.io/component: kibana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elastic
        app.kubernetes.io/component: kibana
    spec:
      # tolerations:
      # - effect: NoSchedule
      #   key: dedicated
      #   operator: Equal
      #   value: SR
      containers:
      - name: kibana
        image: kibana:7.4.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
          name: kibana
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /usr/share/kibana/config
            name: kibana
      volumes:
        - name: kibana
          configMap:
            name: kibana
            defaultMode: 292
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: kibana
spec:
  ports:
  - name: kibana
    protocol: TCP
    port: 5601
  selector:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: kibana