apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      loki {
        url => "http://loki:3100/loki/api/v1/push"
        tenant_id => "default"
        batch_size => 1024
        batch_wait => 5s
        source => "%{host}"
      }
    }